id: I205E07BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T04:35:48+00:00'
last_modified: '2022-06-08T14:12:16.785203+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7841
  title: བསྐལ་བཟང་རྒྱ་མཚོའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1BC9:
      image_group_id: I1KG2776
      title: ''
      total_pages: 848
      order: 1
      base_file: 1BC9.txt
    A800:
      image_group_id: I1KG2777
      title: ''
      total_pages: 374
      order: 2
      base_file: A800.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
