id: P010519
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:53:53.398440
source_metadata:
  id: bdr:W2CZ7841
  title: བསྐལ་བཟང་རྒྱ་མཚོའི་རྣམ་ཐར་
  author: ''
  volumes:
    38283512e23c4b80aed578fa26b97852:
      image_group_id: I1KG2776
      title: ''
      volume_number: 1
      total_pages: 848
      base_file: v001.txt
    dfed69db947149b9a852bdd9226f73da:
      image_group_id: I1KG2777
      title: ''
      volume_number: 2
      total_pages: 374
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
